2022-03-01 23:53:24,764 INFO    MainThread:21808 [wandb_setup.py:_flush():69] setting env: {}
2022-03-01 23:53:24,764 INFO    MainThread:21808 [wandb_setup.py:_flush():69] setting login settings: {}
2022-03-01 23:53:24,764 INFO    MainThread:21808 [wandb_setup.py:_flush():69] setting login settings: {}
2022-03-01 23:53:24,764 INFO    MainThread:21808 [wandb_init.py:_log_setup():334] Logging user logs to W:\rpnn\python\wandb\run-20220301_235324-3pu1c9zk\logs\debug.log
2022-03-01 23:53:24,764 INFO    MainThread:21808 [wandb_init.py:_log_setup():335] Logging internal logs to W:\rpnn\python\wandb\run-20220301_235324-3pu1c9zk\logs\debug-internal.log
2022-03-01 23:53:24,764 INFO    MainThread:21808 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001E32E48B160>
2022-03-01 23:53:24,765 INFO    MainThread:21808 [wandb_init.py:init():367] calling init triggers
2022-03-01 23:53:24,765 INFO    MainThread:21808 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2022-03-01 23:53:24,765 INFO    MainThread:21808 [wandb_init.py:init():416] starting backend
2022-03-01 23:53:24,765 INFO    MainThread:21808 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2022-03-01 23:53:24,771 INFO    MainThread:21808 [backend.py:ensure_launched():123] starting backend process...
2022-03-01 23:53:24,838 INFO    MainThread:21808 [backend.py:ensure_launched():127] started backend process with pid: 2928
2022-03-01 23:53:24,838 INFO    MainThread:21808 [wandb_init.py:init():421] backend started and connected
2022-03-01 23:53:24,883 INFO    MainThread:21808 [wandb_init.py:init():461] updated telemetry
2022-03-01 23:53:24,890 INFO    MainThread:21808 [wandb_init.py:init():480] communicating current version
2022-03-01 23:53:25,774 INFO    MainThread:21808 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-01 23:53:25,774 INFO    MainThread:21808 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2022-03-01 23:53:26,149 INFO    MainThread:21808 [wandb_init.py:init():518] starting run threads in backend
2022-03-01 23:53:26,311 INFO    MainThread:21808 [wandb_run.py:_console_start():1476] atexit reg
2022-03-01 23:53:26,312 INFO    MainThread:21808 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2022-03-01 23:53:26,312 INFO    MainThread:21808 [wandb_run.py:_redirect():1374] Wrapping output streams.
2022-03-01 23:53:26,312 INFO    MainThread:21808 [wandb_run.py:_redirect():1390] Redirects installed.
2022-03-01 23:53:26,312 INFO    MainThread:21808 [wandb_init.py:init():542] run started, returning control to user process
2022-03-01 23:53:26,315 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:53:26,315 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:54:11,835 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:54:11,835 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:54:11,835 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:54:12,591 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:54:12,592 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:54:12,592 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:54:13,588 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:54:13,588 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:54:13,588 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:54:14,509 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:54:14,510 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:54:14,510 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:54:16,014 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:54:16,016 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:54:16,017 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:54:16,972 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:54:17,011 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:54:17,011 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:54:40,573 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:54:40,588 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:54:40,588 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:54:46,800 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:54:48,521 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:54:48,521 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:55:01,393 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:55:01,394 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:55:01,394 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-01 23:55:14,475 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-01 23:55:14,478 INFO    MainThread:21808 [pyagent.py:run():314] Starting sweep agent: entity=None, project=None, count=4
2022-03-01 23:55:15,459 INFO    Thread-14 :21808 [wandb_setup.py:_flush():69] setting env: {'project': 'matrix-factorization', 'entity': 'lubomirkurcak', 'root_dir': 'W:\\rpnn\\python', 'sweep_id': 'moov5s0w', 'run_id': 'ni4v3gv7', 'sweep_param_path': 'W:\\rpnn\\python\\wandb\\sweep-moov5s0w\\config-ni4v3gv7.yaml'}
2022-03-01 23:55:15,459 INFO    Thread-14 :21808 [wandb_init.py:_log_setup():334] Logging user logs to W:\rpnn\python\wandb\run-20220301_235515-ni4v3gv7\logs\debug.log
2022-03-01 23:55:15,459 INFO    Thread-14 :21808 [wandb_init.py:_log_setup():335] Logging internal logs to W:\rpnn\python\wandb\run-20220301_235515-ni4v3gv7\logs\debug-internal.log
2022-03-01 23:55:15,460 INFO    Thread-14 :21808 [wandb_init.py:init():367] calling init triggers
2022-03-01 23:55:15,460 INFO    Thread-14 :21808 [wandb_init.py:init():372] wandb.init called with sweep_config: {'dropout': 0, 'epochs': 50000, 'features': 25, 'fp_emax': 50, 'fp_explim': 'CPFLOAT_EXPRANGE_STOR', 'fp_flip': 'CPFLOAT_NO_SOFTERR', 'fp_p': 0.4553489526223733, 'fp_precision': 13, 'fp_round': 'CPFLOAT_RND_TZ', 'fp_subnormal': 'CPFLOAT_SUBN_RND', 'learning_rate': 0.001, 'loss': 'mean_squared_error', 'momentum_coefficient': 0, 'non_negative': 1, 'weight_decay': 0.0001}
config: {}
2022-03-01 23:55:15,460 INFO    Thread-14 :21808 [wandb_init.py:init():416] starting backend
2022-03-01 23:55:15,460 INFO    Thread-14 :21808 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2022-03-01 23:55:15,462 INFO    Thread-14 :21808 [backend.py:ensure_launched():123] starting backend process...
2022-03-01 23:55:15,524 INFO    Thread-14 :21808 [backend.py:ensure_launched():127] started backend process with pid: 25300
2022-03-01 23:55:15,525 INFO    Thread-14 :21808 [wandb_init.py:init():421] backend started and connected
2022-03-01 23:55:15,535 INFO    Thread-14 :21808 [wandb_run.py:_config_callback():733] config_cb None None {'dropout': 0, 'epochs': 50000, 'features': 25, 'fp_emax': 50, 'fp_explim': 'CPFLOAT_EXPRANGE_STOR', 'fp_flip': 'CPFLOAT_NO_SOFTERR', 'fp_p': 0.4553489526223733, 'fp_precision': 13, 'fp_round': 'CPFLOAT_RND_TZ', 'fp_subnormal': 'CPFLOAT_SUBN_RND', 'learning_rate': 0.001, 'loss': 'mean_squared_error', 'momentum_coefficient': 0, 'non_negative': 1, 'weight_decay': 0.0001}
2022-03-01 23:55:15,536 INFO    Thread-14 :21808 [wandb_init.py:init():461] updated telemetry
2022-03-01 23:55:15,548 INFO    Thread-14 :21808 [wandb_init.py:init():480] communicating current version
2022-03-01 23:55:16,555 INFO    Thread-14 :21808 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-01 23:55:16,556 INFO    Thread-14 :21808 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2022-03-01 23:55:16,918 INFO    Thread-14 :21808 [wandb_init.py:init():518] starting run threads in backend
2022-03-01 23:55:17,085 INFO    Thread-14 :21808 [wandb_run.py:_console_start():1476] atexit reg
2022-03-01 23:55:17,086 INFO    Thread-14 :21808 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2022-03-01 23:55:17,086 INFO    Thread-14 :21808 [wandb_run.py:_redirect():1374] Wrapping output streams.
2022-03-01 23:55:17,086 INFO    Thread-14 :21808 [wandb_run.py:_redirect():1390] Redirects installed.
2022-03-01 23:55:17,086 INFO    Thread-14 :21808 [wandb_init.py:init():542] run started, returning control to user process
2022-03-01 23:55:17,086 INFO    Thread-14 :21808 [wandb_run.py:finish():1135] finishing run lubomirkurcak/matrix-factorization/ni4v3gv7
2022-03-01 23:55:17,087 INFO    Thread-14 :21808 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 1
2022-03-01 23:55:17,087 INFO    Thread-14 :21808 [wandb_run.py:_restore():1418] restore
2022-03-01 23:55:17,623 INFO    Thread-14 :21808 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-03-01 23:55:19,638 INFO    Thread-14 :21808 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4486
  total_bytes: 4486
}

2022-03-01 23:55:20,747 INFO    Thread-14 :21808 [wandb_run.py:_show_files():1790] logging synced files
2022-03-01 23:55:20,750 ERROR   MainThread:21808 [pyagent.py:_run_jobs_from_queue():231] Run ni4v3gv7 errored: TypeError("'int' object is not iterable")
2022-03-01 23:55:21,595 INFO    Thread-18 :21808 [wandb_setup.py:_flush():69] setting env: {'project': 'matrix-factorization', 'entity': 'lubomirkurcak', 'root_dir': 'W:\\rpnn\\python', 'sweep_id': 'moov5s0w', 'run_id': 'mfz78loy', 'sweep_param_path': 'W:\\rpnn\\python\\wandb\\sweep-moov5s0w\\config-mfz78loy.yaml'}
2022-03-01 23:55:21,595 INFO    Thread-18 :21808 [wandb_setup.py:_flush():69] setting login settings: {}
2022-03-01 23:55:21,595 INFO    Thread-18 :21808 [wandb_init.py:_log_setup():334] Logging user logs to W:\rpnn\python\wandb\run-20220301_235521-mfz78loy\logs\debug.log
2022-03-01 23:55:21,595 INFO    Thread-18 :21808 [wandb_init.py:_log_setup():335] Logging internal logs to W:\rpnn\python\wandb\run-20220301_235521-mfz78loy\logs\debug-internal.log
2022-03-01 23:55:21,596 INFO    Thread-18 :21808 [wandb_init.py:init():367] calling init triggers
2022-03-01 23:55:21,596 INFO    Thread-18 :21808 [wandb_init.py:init():372] wandb.init called with sweep_config: {'dropout': 0, 'epochs': 50000, 'features': 25, 'fp_emax': 33, 'fp_explim': 'CPFLOAT_EXPRANGE_STOR', 'fp_flip': 'CPFLOAT_SOFTERR', 'fp_p': 0.3955502430473371, 'fp_precision': 24, 'fp_round': 'CPFLOAT_RND_SP', 'fp_subnormal': 'CPFLOAT_SUBN_USE', 'learning_rate': 0.001, 'loss': 'mean_squared_error', 'momentum_coefficient': 0, 'non_negative': 1, 'weight_decay': 0.0001}
config: {}
2022-03-01 23:55:21,596 INFO    Thread-18 :21808 [wandb_init.py:init():416] starting backend
2022-03-01 23:55:21,596 INFO    Thread-18 :21808 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2022-03-01 23:55:21,598 INFO    Thread-18 :21808 [backend.py:ensure_launched():123] starting backend process...
2022-03-01 23:55:21,672 INFO    Thread-18 :21808 [backend.py:ensure_launched():127] started backend process with pid: 8704
2022-03-01 23:55:21,673 INFO    Thread-18 :21808 [wandb_init.py:init():421] backend started and connected
2022-03-01 23:55:21,683 INFO    Thread-18 :21808 [wandb_run.py:_config_callback():733] config_cb None None {'dropout': 0, 'epochs': 50000, 'features': 25, 'fp_emax': 33, 'fp_explim': 'CPFLOAT_EXPRANGE_STOR', 'fp_flip': 'CPFLOAT_SOFTERR', 'fp_p': 0.3955502430473371, 'fp_precision': 24, 'fp_round': 'CPFLOAT_RND_SP', 'fp_subnormal': 'CPFLOAT_SUBN_USE', 'learning_rate': 0.001, 'loss': 'mean_squared_error', 'momentum_coefficient': 0, 'non_negative': 1, 'weight_decay': 0.0001}
2022-03-01 23:55:21,683 INFO    Thread-18 :21808 [wandb_init.py:init():461] updated telemetry
2022-03-01 23:55:21,691 INFO    Thread-18 :21808 [wandb_init.py:init():480] communicating current version
2022-03-01 23:55:22,582 INFO    Thread-18 :21808 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-01 23:55:22,583 INFO    Thread-18 :21808 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2022-03-01 23:55:22,972 INFO    Thread-18 :21808 [wandb_init.py:init():518] starting run threads in backend
2022-03-01 23:55:23,135 INFO    Thread-18 :21808 [wandb_run.py:_console_start():1476] atexit reg
2022-03-01 23:55:23,135 INFO    Thread-18 :21808 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2022-03-01 23:55:23,135 INFO    Thread-18 :21808 [wandb_run.py:_redirect():1374] Wrapping output streams.
2022-03-01 23:55:23,136 INFO    Thread-18 :21808 [wandb_run.py:_redirect():1390] Redirects installed.
2022-03-01 23:55:23,136 INFO    Thread-18 :21808 [wandb_init.py:init():542] run started, returning control to user process
2022-03-01 23:55:23,136 INFO    Thread-18 :21808 [wandb_run.py:finish():1135] finishing run lubomirkurcak/matrix-factorization/mfz78loy
2022-03-01 23:55:23,136 INFO    Thread-18 :21808 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 1
2022-03-01 23:55:23,136 INFO    Thread-18 :21808 [wandb_run.py:_restore():1418] restore
2022-03-01 23:55:23,666 INFO    Thread-18 :21808 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-03-01 23:55:25,680 INFO    Thread-18 :21808 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4483
  total_bytes: 4483
}

2022-03-01 23:55:26,809 INFO    Thread-18 :21808 [wandb_run.py:_show_files():1790] logging synced files
2022-03-01 23:55:26,813 ERROR   MainThread:21808 [pyagent.py:_run_jobs_from_queue():231] Run mfz78loy errored: TypeError("'int' object is not iterable")
2022-03-01 23:55:27,636 INFO    Thread-22 :21808 [wandb_setup.py:_flush():69] setting env: {'project': 'matrix-factorization', 'entity': 'lubomirkurcak', 'root_dir': 'W:\\rpnn\\python', 'sweep_id': 'moov5s0w', 'run_id': 'bm72rvwv', 'sweep_param_path': 'W:\\rpnn\\python\\wandb\\sweep-moov5s0w\\config-bm72rvwv.yaml'}
2022-03-01 23:55:27,636 INFO    Thread-22 :21808 [wandb_setup.py:_flush():69] setting login settings: {}
2022-03-01 23:55:27,636 INFO    Thread-22 :21808 [wandb_init.py:_log_setup():334] Logging user logs to W:\rpnn\python\wandb\run-20220301_235527-bm72rvwv\logs\debug.log
2022-03-01 23:55:27,636 INFO    Thread-22 :21808 [wandb_init.py:_log_setup():335] Logging internal logs to W:\rpnn\python\wandb\run-20220301_235527-bm72rvwv\logs\debug-internal.log
2022-03-01 23:55:27,637 INFO    Thread-22 :21808 [wandb_init.py:init():367] calling init triggers
2022-03-01 23:55:27,637 INFO    Thread-22 :21808 [wandb_init.py:init():372] wandb.init called with sweep_config: {'dropout': 0, 'epochs': 50000, 'features': 25, 'fp_emax': 30, 'fp_explim': 'CPFLOAT_EXPRANGE_TARG', 'fp_flip': 'CPFLOAT_NO_SOFTERR', 'fp_p': 0.43625404915192983, 'fp_precision': 10, 'fp_round': 'CPFLOAT_NO_RND', 'fp_subnormal': 'CPFLOAT_SUBN_USE', 'learning_rate': 0.001, 'loss': 'mean_squared_error', 'momentum_coefficient': 0, 'non_negative': 1, 'weight_decay': 0.0001}
config: {}
2022-03-01 23:55:27,637 INFO    Thread-22 :21808 [wandb_init.py:init():416] starting backend
2022-03-01 23:55:27,637 INFO    Thread-22 :21808 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn, using: spawn
2022-03-01 23:55:27,639 INFO    Thread-22 :21808 [backend.py:ensure_launched():123] starting backend process...
2022-03-01 23:55:27,704 INFO    Thread-22 :21808 [backend.py:ensure_launched():127] started backend process with pid: 21540
2022-03-01 23:55:27,704 INFO    Thread-22 :21808 [wandb_init.py:init():421] backend started and connected
2022-03-01 23:55:27,714 INFO    Thread-22 :21808 [wandb_run.py:_config_callback():733] config_cb None None {'dropout': 0, 'epochs': 50000, 'features': 25, 'fp_emax': 30, 'fp_explim': 'CPFLOAT_EXPRANGE_TARG', 'fp_flip': 'CPFLOAT_NO_SOFTERR', 'fp_p': 0.43625404915192983, 'fp_precision': 10, 'fp_round': 'CPFLOAT_NO_RND', 'fp_subnormal': 'CPFLOAT_SUBN_USE', 'learning_rate': 0.001, 'loss': 'mean_squared_error', 'momentum_coefficient': 0, 'non_negative': 1, 'weight_decay': 0.0001}
2022-03-01 23:55:27,714 INFO    Thread-22 :21808 [wandb_init.py:init():461] updated telemetry
2022-03-01 23:55:27,718 INFO    Thread-22 :21808 [wandb_init.py:init():480] communicating current version
2022-03-01 23:55:28,614 INFO    Thread-22 :21808 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-01 23:55:28,615 INFO    Thread-22 :21808 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2022-03-01 23:55:28,997 INFO    Thread-22 :21808 [wandb_init.py:init():518] starting run threads in backend
2022-03-01 23:55:29,185 INFO    Thread-22 :21808 [wandb_run.py:_console_start():1476] atexit reg
2022-03-01 23:55:29,185 INFO    Thread-22 :21808 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2022-03-01 23:55:29,186 INFO    Thread-22 :21808 [wandb_run.py:_redirect():1374] Wrapping output streams.
2022-03-01 23:55:29,186 INFO    Thread-22 :21808 [wandb_run.py:_redirect():1390] Redirects installed.
2022-03-01 23:55:29,186 INFO    Thread-22 :21808 [wandb_init.py:init():542] run started, returning control to user process
2022-03-01 23:55:29,186 INFO    Thread-22 :21808 [wandb_run.py:finish():1135] finishing run lubomirkurcak/matrix-factorization/bm72rvwv
2022-03-01 23:55:29,186 INFO    Thread-22 :21808 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 1
2022-03-01 23:55:29,186 INFO    Thread-22 :21808 [wandb_run.py:_restore():1418] restore
2022-03-01 23:55:29,693 INFO    Thread-22 :21808 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-03-01 23:55:31,706 INFO    Thread-22 :21808 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4487
  total_bytes: 4487
}

2022-03-01 23:55:32,825 INFO    Thread-22 :21808 [wandb_run.py:_show_files():1790] logging synced files
2022-03-01 23:55:32,828 ERROR   MainThread:21808 [pyagent.py:_run_jobs_from_queue():231] Run bm72rvwv errored: TypeError("'int' object is not iterable")
2022-03-01 23:55:32,829 ERROR   MainThread:21808 [pyagent.py:_run_jobs_from_queue():242] Detected 3 failed runs in the first 60 seconds, killing sweep.
2022-03-01 23:55:32,831 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-01 23:55:32,832 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-02 00:15:50,564 INFO    MainThread:21808 [wandb_init.py:_resume_backend():256] resuming backend
2022-03-02 00:15:50,937 INFO    MainThread:21808 [wandb_init.py:_pause_backend():247] pausing backend
2022-03-02 00:15:50,937 INFO    MainThread:21808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2022-03-02 00:15:58,660 INFO    MainThread:21808 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2022-03-02 00:15:58,660 INFO    MainThread:21808 [wandb_run.py:_restore():1418] restore
2022-03-02 00:15:58,929 INFO    MainThread:21808 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-03-02 00:16:00,944 INFO    MainThread:21808 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8022
  total_bytes: 8022
}

2022-03-02 00:16:02,046 INFO    MainThread:21808 [wandb_run.py:_show_files():1790] logging synced files
